services:
  duplicati:
    container_name: duplicati
    image: ghcr.io/linuxserver/duplicati:latest
    ports:
      - 8200:8200
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SETTINGS_ENCRYPTION_KEY=${SETTINGS_ENCRYPTION_KEY}
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI__WEBSERVICE_PASSWORD}
    volumes:
      - ./config:/config
      - /mnt/nas_backups:/backups
      - /home/genbyte:/source
    restart: always

